version: 2
jobs:
  build:
    working_directory: ~/go-demo
    docker:
      - image: circleci/golang:1.8.1
        environment:
          GOPATH=/home/circleci/go-demo
      - image: postgres:9.6.2
      
    steps:
      - checkout
      - run: go get -t -d -v ./...
      - run: go build -v
      - save_cache:
          key: src-{{ .Branch }}-{{ checksum "main.go" }}
          paths:
            - "src/"
  test:
    working_directory: ~/go-demo
    docker:
      - image: circleci/golang:1.8.1
        environment:
          GOPATH=/home/circleci/go-demo
      - image: postgres:9.6.2
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          key: src-{{ .Branch }}-{{ checksum "main.go" }}
      - run: go test ./... -v $(go list | grep -v vendor)
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build